### ISSUE TITLE
reCaptcha validation

### ISSUE THREAD

**Issue by luisalrp** [jbesw/aws-serverless-form-handler#1]
Hi James,

First of all, thanks for building it. I have been using for a month and it works great. I would like to add reCaptcha function and I researched other AWS Serverless Apps Repositories but I don't get hot to do it.

I open the issue as an enhancement for someone with better programing skills than me.

Best regards.

**Comment by jbesw** [comment]
Sorry, I only just saw this issue - I'll see if I can work a reCAPTCHA example into a future project. Thanks for the idea.
