### ISSUE TITLE
Error forwarding to Gmail address

### ISSUE THREAD

**Issue by ghost** [jbesw/aws-serverless-form-handler#3]
While submitting my form to my Gmail account from SES I am seeing this error :

**Be careful with this message**

This may be a spoofed message. The message claims to have been sent from your account, but Gmail couldn't verify the actual source. Avoid clicking links or replying with sensitive information …

Thanks

**Comment by jbesw** [comment]
This is really about fine-tuning your SES configuration and usage to best avoid a spam filter. You should ensure you have followed all the steps for DCIM configuration of a domain and some of the advice list here: 

- https://docs.aws.amazon.com/ses/latest/DeveloperGuide/sending-concepts-deliverability.html
- https://docs.aws.amazon.com/ses/latest/DeveloperGuide/verify-domains.html

HTH,
James
